[package]
name = "passgen"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Zach Griffin (0xTas) <root@0xtas.dev>"]


[profile.release]
lto = true
strip = true


[dependencies]
rand = "0.8.5"
clap = {version = "4.1.7", features = ["derive"]}
